### ISSUE TITLE
Any idea how to get this table to generate using more than one core?

### ISSUE THREAD

**Issue by marklit** [duckdblabs/duckdb_spatial#31]
The datasets I worked with in #30 are being used in this example. I sampled 1K records from the roads dataset and I'm using all 76 records from the tourist spots dataset.

```sql
D select count(*) from ms_roads;
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│      4628534 │
└──────────────┘
D select count(*) from tourist_spots;
┌──────────────┐
│ count_star() │
│    int64     │
├──────────────┤
│           76 │
└──────────────┘

create table roads2 as select * from ms_roads limit 1000;
```

When I execute the following on macOS, htop reports the DuckDB process hitting 99% but not going beyond that despite there being 8 cores available.

```sql
CREATE OR REPLACE TABLE joined1 AS
    SELECT *
    FROM roads2
    JOIN tourist_spots
    ON ST_WITHIN(ST_TRANSFORM(roads2.geom,
                              'EPSG:4326',
                              'EPSG:7844'),
                 tourist_spots.wkb_geometry);
```

The above takes a lot longer than I'd expect to finish as well.

```
Run Time (s): real 212.480 user 204.115424 sys 5.362578
```

Switching the table being transformed takes even longer though after ~5 minutes I can see htop show DuckDB's CPU usage jump to 200%.

```sql
CREATE OR REPLACE TABLE joined2 AS
    SELECT *
    FROM roads2
    JOIN tourist_spots
    ON ST_WITHIN(ST_TRANSFORM(tourist_spots.wkb_geometry,
                              'EPSG:7844',
                              'EPSG:4326'),
                 roads2.geom);
```

```
Run Time (s): real 390.354 user 470.561769 sys 19.437731
```

I've tried pre-baking the projection (2.7 seconds for 70 rows) but the join still takes a long time.

```sql
CREATE TABLE tourist_spots2 AS
    SELECT ST_TRANSFORM(tourist_spots.wkb_geometry,
                              'EPSG:7844',
                              'EPSG:4326') geom
    FROM tourist_spots;
```

```
Run Time (s): real 2.700 user 4.731631 sys 0.293701
```

```sql
CREATE OR REPLACE TABLE joined1 AS
    SELECT *
    FROM roads2
    JOIN tourist_spots2
    ON ST_WITHIN(roads2.geom,
                 tourist_spots2.geom);
```

```
Run Time (s): real 222.399 user 214.080460 sys 5.254669
```

**Comment by Maxxen** [comment]
I think you're only seeing one core being used because 1k records is enough to fit within a single DuckDB vector (that's 2048 rows), which is the smallest unit of work DuckDB uses to distribute work. I don't think we have an easy way to change the vector size at runtime, but there is a #define in `src/include/duckdb/common/vector_size.hpp` that controls it.

It might be possible to optimise `ST_Transform` some more, but I'll have to peek around the proj c api.

All spatial predicates like `ST_Within` are expected to be slow since we don't have any spatial indexes yet, I.E. the join has to brute force and check every combination even if two geometries are known to be far away from each other. 

I see that you're operating directly on `WKB_BLOB`s, that's going to require an extra cast to `GEOMETRY` which is a full allocation->serialization->deserialisation step. Ideally you should convert them into geometry with `ST_GeomFromWKB` when you create the table. Perhaps having WKB_BLOB be implicitly castable to geometry causes this confusion.

**Comment by marklit** [comment]
I transformed both source tables first.

```sql
CREATE OR REPLACE TABLE roads2 AS
    SELECT ST_GEOMFROMWKB(geom) geom
    FROM ms_roads
    LIMIT 1000;

CREATE OR REPLACE TABLE tourist_spots2 AS
    SELECT ST_TRANSFORM(ST_GEOMFROMWKB(tourist_spots.wkb_geometry),
                        'EPSG:7844',
                        'EPSG:4326') geom
    FROM tourist_spots;
```

The following finished in `Run Time (s): real 218.772 user 206.269061 sys 7.407438`.

```sql
CREATE OR REPLACE TABLE joined1 AS
    SELECT *
    FROM roads2
    JOIN tourist_spots2
        ON ST_WITHIN(roads2.geom,
                     tourist_spots2.geom);
```

**Comment by Maxxen** [comment]
Ok, I actually have an idea of what may cause this, hold on.

**Comment by marklit** [comment]
I rebuilt with today's master branch with `make release` and I'm getting 6-800% now.

<img width="1241" alt="Screenshot 2023-04-07 at 16 51 45" src="https://user-images.githubusercontent.com/359316/230620284-39803608-77c5-432c-9974-2c71e3aae026.png">

`Run Time (s): real 179.119 user 1027.150289 sys 31.586017`

Oddly enough the execution time has decreased but not by 8x. Still, it's an improvement.

**Comment by Maxxen** [comment]
Great! The underlying issue is that the join is not aware of the spatial relationships - it can't partition/hash/index the candidates, which causes it to fall back to a "compare everything with everything" style join, where the ST_Within becomes a bottleneck. This is something we want to change but it requires some changes in core DuckDB to allow extensions to push custom physical operators, we'll try to pick it up in a couple of weeks.
