### ISSUE TITLE
Questions for spherical calculations and spatial index

### ISSUE THREAD

**Issue by gaoyuanning** [duckdblabs/duckdb_spatial#46]
Thanks for providing the excellent spatial extension for duckdb. For the current version, I have some concerns.

1. For spherical calculation, will we introduce another third-library to support it? Or use some functions in geos library (Sorry, I did not find the releated spherical types and functions in geos)
2. Clickhouse use boost::geometry, which also contains the most of geospatial function. Could you give some insights for the use of geos instead of boost::geometry. 
3. Assume the final version is R-tree for the spatial index, will we integrate the R-tree into duckdb? From my point, indexes is tightly releated to the storage layer and the runtime layer in database, so we might not use the third-library to implement R-tree.

Looking forward to reply.

**Comment by Maxxen** [comment]
Hi! Great questions!

1. I was hoping I would be able to hack together some of the basics myself at some point (distance, area) and cast to cartesian for the more advanced operations. Which seems to be the strategy used by PostGIS. I also really like S2.

2. I mostly went with GEOS due to it already being part of the GDAL stack, and I  figured that it would be easier to achieve standards compliance since it itself is OGC compliant. That said, I do think we should take another look at boost::geometry, I'm already toying with writing generic algorithms since I want to try to support both columnar and binary geometry types/storage. My only concern is getting this extension to compile on c++14 (duckdb backports a couple of things into c++11). 

3. We are looking into enabling a way for extensions to provide their own index implementations, but that's probably not going to happen very soon. However, I do think we will be using a combination of optimiser rules and custom operators to construct and use spatial indexes ad-hoc when e.g. doing joins much sooner. This will also require som work in core DuckDB though.

**Comment by gaoyuanning** [comment]
>

**Comment by gaoyuanning** [comment]
> 

Thanks very much for your reply, which is very insightful.
