### ISSUE TITLE
Geometry from HEX string

### ISSUE THREAD

**Issue by jannekeskitalo** [duckdblabs/duckdb_spatial#93]
I have geometries dumped from postgres in WKB hex format to CSV. Is there a way to convert these to DuckDB geometry -type?

There's no function for: ST_GeomFromHEXWKB()

The source WKB hex strings look like this:

`0103000020FB0B000001000000040000003A0D9D1BD96A2041DD7785E876C8594104540619C66A2041BB3961E381C85941D9FE2983826A2041E0BCADCA81C859413A0D9D1BD96A2041DD7785E876C85941`

**Comment by mtravis** [comment]
You could parse the file using geopandas and output as a WKT

https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.from_wkb.html#geopandas-geoseries-from-wkb

**Comment by Maxxen** [comment]
Hi! Thanks for raising this issue. The lack of wkbhex->geometry conversion when the other way around exists seems like an oversight on my part. I'll see what I can do.

**Comment by jannekeskitalo** [comment]
That's kind of what I'm doing now. I use Duckdb to read the data from S3, in python convert HEXWKB to shapely geometries and then to GeoPandas DF. This gets used in further rasterio processing. It works, but optimal would be to get duckdb query results directly as GeoPandas DF.

Mostly I'm looking here a way to handle postgres COPY data -dumps which are HEXWKB by default. We have a lot of this type of data as we shuffle datasets back and forth between postgres and S3.

**Comment by mtravis** [comment]
> That's kind of what I'm doing now. I use Duckdb to read the data from S3, in python convert HEXWKB to shapely geometries and then to GeoPandas DF. This gets used in further rasterio processing. It works, but optimal would be to get duckdb query results directly as GeoPandas DF.
> 
> Mostly I'm looking here a way to handle postgres COPY data -dumps which are HEXWKB by default. We have a lot of this type of data as we shuffle datasets back and forth between postgres and S3.

Out of interest is there a reason you dump the data as HEXWKB instead of WKB?

**Comment by Maxxen** [comment]
I've implemented `ST_GeomFromHEXWKB` in #94. In the future (maybe as part of #1) we should probably look into creating a native table function to read postgis dumps directly.

**Comment by Maxxen** [comment]
Ah crap, I was right, [postgis dumps EWKB](https://postgis.net/docs/using_postgis_dbmanagement.html#EWKB_EWKT). I might be able to squeeze in EWKB/HEXEWKB support later this week.

**Comment by mtravis** [comment]
That would be fantastic. Do you think it would be possible to read pgdump
files directly then? The pgdump driver only seems to have a create
function.

**Comment by mtravis** [comment]
> I've implemented `ST_GeomFromHEXWKB` in #94. In the future (maybe as part of #1) we should probably look into creating a native table function to read postgis dumps directly.
> 
> Note that this won't work with _extended_ EWKB/HEXEWKB, which I suspect is what postgis actually use in their dumps since they store SRID's in their geometry. However we probably want to store SRID's in our geometry type as well at some point, so it's just a question of time until we'll support ewkb/ewkt as well.

That would be fantastic. Do you think it would be possible to read pgdump
files directly then? The pgdump driver only seems to have a create
function.

**Comment by Maxxen** [comment]
> That would be fantastic. Do you think it would be possible to read pgdump files directly then? The pgdump driver only seems to have a create function.

In general I think the difference between the sql supported in postgres and duckdb is too great to be able to just read a pgdump straight up using the CLI's `.read` command, but we may be able to do some sort of special function here in the spatial extension that just "extracts" the geometries/columns from a pgdump, without necessarily applying or creating all the pragmas/configs/indexes/constraints in the dump file by just ignoring every statement that's not a `CREATE TABLE ...` `AddGeometryColumn(...)` and `INSERT INTO ...`.

Would you guys mind elaborating a bit and explain your current workflow? I'm curious how common this use case is. I suppose you're normally storing these on e.g. s3 as a product of some sort of backup/cron job?

**Comment by mtravis** [comment]
In terms of our workflow we take data from various sources and run it through postgis and saving out as a pgdump to s3. Thinking about it though we partition the data over several g-zipped files so that would even more complexity. 

I  still think this would be a useful addition though and happy to support and test when needed. I'm keen to learn more about DuckDB as it fits in really well with our workflow.

**Comment by Maxxen** [comment]
Alright, `ST_GeomFromHEXWKB` and `ST_GeomFromHEXEWKB` has been merged in #94. For now they do exactly the same thing since we will parse geometries with SRID's attached but the SRID field is simply ignored. While reading pgdumps directly does sound interesting I think its best continued on in a separate issue/discussion.

**Comment by jannekeskitalo** [comment]
We use ephemeral postgres instances to run complex spatial transformations, but keep bulk of the data in S3. Data is moved between s3<->postgres with a custom loader that runs parallel postgres COPY -commands. COPY exports geometries as HEXWKB.

**Comment by chuckwondo** [comment]
@Maxxen, thanks so much for getting `ST_GeomFromHEXWKB` and `ST_GeomFromHEXEWKB` implemented! Would you mind cutting a new release so we can use them?

**Comment by Maxxen** [comment]
Yes! I'm finishing up some last CI issues but will cut a new release before the week is over.

**Comment by chuckwondo** [comment]
@Maxxen, nudge, nudge :-)

**Comment by Maxxen** [comment]
Apologies! This should be available when using the latest duckdb nightly builds, but since there's been some breaking changes already we're probably not going to issue a backport into v0.8.1. There is a new major release (0.9.0) scheduled for early September though which will have an accompanying spatial release including all the fixes and features up to that point.

We're thinking of how to handle this going forward, but I think after 0.9.0 we will at least attempt to build for the latest nightly and the last stable release as long as possible until the diff in core duckdb inevitable becomes too big.

**Comment by chuckwondo** [comment]
Fantastic! Thank you again for all of your hard work on this!
